{
    "openapi": "3.0.2",
    "info": {
        "title": "nsmm-api",
        "version": "1.0.0"
    },
    "paths": {
        "/gateways": {
            "description": "Endpoint for retrieving all gateways or create a new gateway",
            "get": {
                "parameters": [
                    {
                        "name": "sliceId",
                        "description": "unique identifier of the slice",
                        "schema": {
                            "type": "string"
                        },
                        "in": "query",
                        "required": false
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ResponseGatewaysList"
                                }
                            }
                        },
                        "description": "- All gateways created \n- the gateway of the requested slice"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "No gatewaysfound"
                    }
                }
            },
            "post": {
                "requestBody": {
                    "description": "Parameters to define a new gateway: private-subnet, slice-id",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PostGateway"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ResponseGateway"
                                }
                            }
                        },
                        "description": "Gateway for slice correctly created"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "JSON body not correct"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "- If a gateway for requested slice already exists\n- the subnet is already in use"
                    }
                }
            }
        },
        "/gateways/{id}": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ResponseGateway"
                                }
                            }
                        },
                        "description": "gateway details"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "- requested gateway does not exist"
                    }
                }
            },
            "delete": {
                "responses": {
                    "204": {
                        "description": "correctly removed gateway"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "- requested gateway does not exist"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "impossibile to remove a gateway, which could be in use or already configured"
                    }
                }
            },
            "parameters": [
                {
                    "name": "id",
                    "description": "gateway unique identifier",
                    "schema": {
                        "type": "integer"
                    },
                    "in": "path",
                    "required": true
                }
            ]
        },
        "/gateways/{id}/configuration": {
            "description": "Endpoint to put/retrieve and delete a configuration of a gateway, which consist of setting the external and management-ip, plus configuring the VPN server",
            "get": {
                "responses": {
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "- configuration for the gateway of the slice not found \n- gateway does not exists"
                    },
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/GatewayConfiguration"
                                }
                            }
                        },
                        "description": "Configuration of the requested gateway,, which is basically the GatewayVM id, its floatingIP and the management info"
                    }
                },
                "description": ""
            },
            "put": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/GatewayConfiguration"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "json not correct"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "If the gateway can't be configured (already configured or in error state)"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "if gateway does not exist"
                    },
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/GatewayConfiguration"
                                }
                            }
                        },
                        "description": "New configuration created"
                    }
                }
            },
            "delete": {
                "responses": {
                    "204": {
                        "description": "correct removal"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "impossibile to delete configuration (VPN server running)"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "- configuration for the gateway does not exist\n- the gateway does not exist"
                    }
                }
            },
            "parameters": [
                {
                    "name": "id",
                    "schema": {
                        "type": "integer"
                    },
                    "in": "path",
                    "required": true
                }
            ]
        },
        "/gateways/{id}/vpn/connections": {
            "description": "Endpoint to retrieve all active VPN connections and create new VPN connections",
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ResponseGatewayVPNConnectionsList"
                                }
                            }
                        },
                        "description": "List of all VPN connection established by the requested gateway"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "- The request gateway does not exist"
                    }
                }
            },
            "post": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PostGatewayVPNConnection"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "- The requested gateway does not exist\n- The requested gateway is not configured\n- The requested gateway has not the VPN server configured"
                    },
                    "204": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ResponseGatewayVPNConnection"
                                }
                            }
                        },
                        "description": "request to delete the gateway connection accepted"
                    }
                }
            },
            "parameters": [
                {
                    "name": "id",
                    "schema": {
                        "type": "integer"
                    },
                    "in": "path",
                    "required": true
                }
            ]
        },
        "/gateways/{id}/vpn/connections/{connectionid}/": {
            "description": "Endpoint to manage a single VPN connection",
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ResponseGatewayVPNConnection"
                                }
                            }
                        },
                        "description": "Connection details"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "- requested connection does not exist\n- requested gateway does not exist"
                    }
                }
            },
            "delete": {
                "responses": {
                    "204": {
                        "description": "correctly requested removal of a VPN connection"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/ErrorResponse"
                                }
                            }
                        },
                        "description": "- request connection does not exist\n- requested gateway does not exist"
                    }
                }
            },
            "parameters": [
                {
                    "name": "id",
                    "schema": {
                        "type": "integer"
                    },
                    "in": "path",
                    "required": true
                },
                {
                    "name": "connectionid",
                    "schema": {
                        "type": "integer"
                    },
                    "in": "path",
                    "required": true
                }
            ]
        }
    },
    "components": {
        "schemas": {
            "ErrorResponse": {
                "title": "Root Type for ErrorResponseGatewayNotExists",
                "description": "Error response\n",
                "required": [
                    "error"
                ],
                "type": "object",
                "properties": {
                    "error": {
                        "type": "string"
                    }
                },
                "example": {
                    "error": "gateway for requested slice does not exists"
                }
            },
            "ResponseGatewayVPNConnectionsList": {
                "title": "Root Type for ResponseGatewayVPNConnectionsList",
                "description": "",
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/ResponseGatewayVPNConnection"
                },
                "example": [
                    {

                    },
                    {

                    }
                ]
            },
            "ResponseGatewaysList": {
                "title": "Root Type for ResponseGatewaysListObject",
                "description": "",
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/ResponseGateway"
                },
                "example": [
                    {
                        "id": 81,
                        "slice-id": "some text",
                        "subnet": "some text",
                        "status": "some text"
                    },
                    {
                        "id": 94,
                        "slice-id": "some text",
                        "subnet": "some text",
                        "status": "some text"
                    }
                ]
            },
            "ResponseGateway": {
                "title": "Root Type for GatewayObject",
                "description": "Object describing gateway",
                "required": [
                    "id",
                    "slice-id",
                    "subnet",
                    "status",
                    "vim-name"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "description": "gateway unique identifier",
                        "type": "integer"
                    },
                    "slice-id": {
                        "description": "slice unique identifier",
                        "type": "string"
                    },
                    "subnet": {
                        "type": "string",
                        "example": "192.168.1.16/29"
                    },
                    "status": {
                        "description": "current status of the gateway",
                        "type": "string"
                    },
                    "vim-name": {
                        "description": "ref to the vim where to create the gateway",
                        "type": "string"
                    }
                },
                "example": {
                    "id": 14,
                    "slice-id": "some text",
                    "subnet": "some text",
                    "status": "some text",
                    "vim-name": "some text"
                }
            },
            "PostGatewayVPNConnection": {
                "title": "Root Type for PostGatewayConnectionBody",
                "description": "Set of information needed to create a VPN connection",
                "required": [
                    "role",
                    "public-key",
                    "subnet-to-redirect",
                    "allowed-ips"
                ],
                "type": "object",
                "properties": {
                    "role": {
                        "description": "Role of the VPN server, if it acts as a SERVER or a CLIENT in the connection creation",
                        "type": "string",
                        "example": "CLIENT,\nSERVER\n"
                    },
                    "remote-server-ip": {
                        "description": "if role == CLIENT",
                        "type": "string"
                    },
                    "remote-server-port": {
                        "description": "if role == CLIENT",
                        "type": "string"
                    },
                    "subnet-to-redirect": {
                        "description": "",
                        "type": "string"
                    },
                    "public-key": {
                        "description": "public-key of client or server, based on the ROLE field",
                        "type": "string"
                    },
                    "allowed-ips": {
                        "description": "list of IPv4 addresses with CIDR masks from which incoming traffic for this peer is allowed and to which outgoing traffic for this peer is directed",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "example": {
                    "role": "some text",
                    "remote-server-ip": "some text",
                    "remote-server-port": "some text",
                    "subnet-to-redirect": "some text",
                    "public-key": "some text",
                    "allowed-ips": [
                        "some text",
                        "some text"
                    ]
                }
            },
            "PostGateway": {
                "title": "Root Type for PostGatewayBody",
                "description": "Subnet of the private net",
                "required": [
                    "subnet",
                    "slice-id",
                    "vim-name"
                ],
                "type": "object",
                "properties": {
                    "subnet": {
                        "description": "private network subnet",
                        "type": "string",
                        "example": "192.168.1.16/29"
                    },
                    "slice-id": {
                        "description": "slice unique identifier",
                        "type": "string"
                    },
                    "vim-name": {
                        "description": "ref to the vim where to create the gateway",
                        "type": "string"
                    }
                },
                "example": {
                    "slice-id": "example",
                    "vim-name": "openstack",
                    "subnet": "192.168.1.16/29"
                }
            },
            "GatewayConfiguration": {
                "title": "Root Type for GatewayConfiguration",
                "description": "",
                "required": [
                    "external-ip",
                    "management-ip",
                    "management-port",
                    "vpn-server-port",
                    "vpn-server-interface"
                ],
                "type": "object",
                "properties": {
                    "external-ip": {
                        "type": "string"
                    },
                    "management-ip": {
                        "description": "",
                        "type": "string"
                    },
                    "management-port": {
                        "description": "",
                        "type": "string"
                    },
                    "vpn-server-port": {
                        "description": "",
                        "type": "string"
                    },
                    "vpn-server-interface": {
                        "description": "",
                        "type": "string"
                    }
                },
                "example": {
                    "external-ip": "some text",
                    "management-ip": "some text",
                    "management-port": "some text",
                    "vpn-server-port": "some text",
                    "vpn-server-interface": "some text"
                }
            },
            "ResponseGatewayVPNConnection": {
                "description": "Set of information needed to create a VPN connection",
                "required": [
                    "id"
                ],
                "type": "object",
                "properties": {
                    "role": {
                        "description": "Role of the VPN server, if it acts as a SERVER or a CLIENT in the connection creation",
                        "type": "string",
                        "example": "CLIENT,\nSERVER\n"
                    },
                    "remote-server-ip": {
                        "description": "if role == CLIENT",
                        "type": "string"
                    },
                    "remote-server-port": {
                        "description": "if role == CLIENT",
                        "type": "string"
                    },
                    "subnet-to-redirect": {
                        "description": "",
                        "type": "string"
                    },
                    "public-key": {
                        "description": "public-key of client or server, based on the ROLE field",
                        "type": "string"
                    },
                    "allowed-ips": {
                        "description": "list of IPv4 addresses with CIDR masks from which incoming traffic for this peer is allowed and to which outgoing traffic for this peer is directed",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "id": {
                        "description": "",
                        "type": "integer"
                    }
                },
                "example": {
                    "role": "some text",
                    "remote-server-ip": "some text",
                    "remote-server-port": "some text",
                    "subnet-to-redirect": "some text",
                    "public-key": "some text",
                    "allowed-ips": [
                        "some text",
                        "some text"
                    ],
                    "id": 39
                }
            }
        }
    }
}